### PR TITLE
Implement support for network load balancers in addition to application load balancers

### PR DESCRIPTION
**Pull request by JonRoma**

### CODE REVIEW

**Comment by JonRoma** [comment]
@ddriddle, would you be able to provide a non-exhaustive preliminary review of this PR? Note that it is a **draft**, and I therefore do not claim it is ready for prime time. :-)

*Caveat lector:*

* The documentation has not been completely updated, pending additional code changes.
* AWS and Terraform documentation describe a "gateway load balancer". This is entirely unsupported in our module, and you will see "TODO" and "FIXME" notices to that effect in the code. This needs better documentation, and perhaps should cause a validation error in newer versions of Terraform.
* To refresh your memory if necessary:
    * ALB is layer 7, and passes HTTP/HTTPS traffic to its listeners.
    * NLB is layer 4, and passes TCP/IP traffic to its listeners.
* I need to understand the pertinence of ACM certificates, if any, with network load balancers. I haven't done much reading on this subject in months.
* In order to build a first incarnation of this refactored module, I deferred some of the logic  for NLBs in some of the `for_each` statements in the code. These intentional omissions are something I now need to circle back around to resolve, hopefully with your help.
* I changed the `ports` variable to a map of maps rather than a list of maps. Part of my reasoning was that the port number is a natural key since it is by definition unique. However, the more important reason is that doing this enables use of Terraform's `for_each` in place of `count`. This is beneficial not only because the created resource names now contain the key (port number), making it self-evident what is attached to what. More important, this change means that ports can be added to and removed from the map without causing a momentary interruption of service for other ports that would otherwise be necessary as a result of Terraform shuffling the indexes generated with the use of `count` whenever the list changes size.
* I didn't touch the `secure_ports` stuff, and I think that once we better understand the relationship of certificates and security groups to NLBs, that will come out in the wash.

If you would like to look at examples of code in `as-aws-test` that use the refactored code in this fork, please see [this directory in my fork](https://github.com/JonRoma/as-aws-test/tree/feature/vpc3/us-east-2/vpc3/lb). You'll see an example for both ALB and NLB options here.

I would like to discuss next week if you have time. Thanks!

**Review by cmaturi — COMMENTED** [review]
Looks good Jon! As I am not an expert in terraform I reviewed all the files with the best of my ability and didn't see anything obvious.

**Comment by JonRoma** [comment]
> Looks good Jon! As I am not an expert in terraform I reviewed all the files with the best of my ability and didn't see anything obvious.

Thanks, Kala. I'm sure you saw my comment to @ddriddle indicating the limitations of the work so far. Have a good weekend!

**Comment by JonRoma** [comment]
This should close #13.

**Comment by JonRoma** [comment]
The customer no longer needs a network load balancer, so we're abandoning this work.

**Pull request closed without merging**
